### ISSUE TITLE
D8 install via Vagrant

### ISSUE THREAD

**Issue by achoura** [previousnext/agov#842]
Dear
i'm kind of stucked in the process of installing the agov dist with the branch 8.x-1.x

* if a follow the instructions on the README file , just composer install will run otherwise, there are no gem file to run  `>> bundle` 
*  i've passed that and installed nodejs and npm on the lamp vagrant box
* then `>>phing` can't run either because there is no build.xml file

404 not found in the browser, still searching for way to run this distrib 

thank you for your help

**Comment by kimpepper** [comment]
For building a site based on aGov, you can simply download it from the project page https://www.drupal.org/project/agov

For contributing to aGov, we've been doing some active development on switching from phing to make, removing front-end reliance on Ruby, and adding composer support. We'll make sure to update the README before we get a beta release out.
